# Generated by Django 4.0.6 on 2022-07-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(choices=[('pending', 'pending'), ('completed', 'completed')]),
        ),
    ]
