# Generated by Django 4.0.6 on 2022-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], max_length=10),
        ),
    ]
